name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up GPG keys
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      - name: Build with Maven
        run: mvn clean install -Dgpg.keyname=$GPG_PRIVATE_KEY -Dgpg.passphrase=$GPG_PASSPHRASE

      - name: Run tests
        run: mvn test
